USE [ClusterDWH]
GO
/****** Object:  StoredProcedure [off].[MERGE_TL_DIM_PRODUCT]    Script Date: 8/3/2026 1:24:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [off].[MERGE_TL_DIM_PRODUCT] (@inDIMProcessDate datetime,@inProcessDatetime datetime)
as 
BEGIN

DECLARE @CNT_PROCESSED	int = 0 ;
DECLARE @V_ACT_DATE_KEY int;
DECLARE @V_NEXT_DATE_KEY int;
DECLARE @V_CNT INT;
DECLARE @DIMProcessDate DATETIME;

SELECT @DIMProcessDate = max(valid_from) from [off].IN_CRM_Product_DIM;

SELECT @V_ACT_DATE_KEY =  CAST(CONVERT(NVARCHAR(6), @DIMProcessDate, 112) AS INTEGER);
SELECT @V_NEXT_DATE_KEY = CAST(CONVERT(NVARCHAR(6), DATEADD(month, 1,@DIMProcessDate ), 112) AS INTEGER);

--STATIC DIMENSIONS
-------------------------------------------
 -- CATEGORY
 INSERT INTO [off].[TL_DIM_PRODUCT_CATEGORY] (PRODUCT_CATEGORY_NAME, INSERTED_DATETIME)
		SELECT DISTINCT CATEGORY,getdate() FROM [off].IN_CRM_Product_DIM where  VALID_TO = '9999-12-31 23:59:59.000' 
		AND  CATEGORY NOT IN (SELECT PRODUCT_CATEGORY_NAME FROM [off].[TL_DIM_PRODUCT_CATEGORY]);

 -- MANUFACTURER
  INSERT INTO [off].[TL_DIM_PRODUCT_MANUFACTURER] ( PRODUCT_MANUFACTURER_NAME, INSERTED_DATETIME)
		SELECT distinct iSnull(MANUFACTURER,'COMPETITIVE ') AS MANUFACTURER, getdate() FROM [off].IN_CRM_Product_DIM where  VALID_TO = '9999-12-31 23:59:59.000' 
		AND  iSnull(MANUFACTURER,'COMPETITIVE ') NOT IN (SELECT PRODUCT_MANUFACTURER_NAME FROM [off].[TL_DIM_PRODUCT_MANUFACTURER]);

-- GENERAL SALES ORGANIZATION
  INSERT INTO [off].[TL_DIM_PRODUCT_GENERAL_SALES_ORGANIZATION] (PRODUCT_GENERAL_SALES_ORGANIZATION_NAME, INSERTED_DATETIME)
		SELECT distinct ISNULL(SALES_ORGANIZATION, 'JTI') AS MANUFACTURER, getdate() FROM [off].IN_CRM_Product_DIM where  VALID_TO = '9999-12-31 23:59:59.000' 
		AND  ISNULL(SALES_ORGANIZATION, 'JTI') NOT IN (SELECT PRODUCT_GENERAL_SALES_ORGANIZATION_NAME FROM [off].[TL_DIM_PRODUCT_GENERAL_SALES_ORGANIZATION]);

--L1 - Sales Organization (JTI SK)
 INSERT INTO  [off].[TL_DIM_PRODUCT_SALES_ORGANIZATION](CODE,INTEGRATION_ID,PRODUCT_SALES_ORGANIZATION_NAME,INSERTED_DATETIME)
		SELECT distinct CODE,INTEGRATION_ID,NAME, getdate() FROM [off].IN_CRM_Product_DIM where  VALID_TO = '9999-12-31 23:59:59.000' AND LEVEL = 'Sales Organization'
		AND  CODE+'~'+INTEGRATION_ID+'~'+NAME NOT IN (SELECT CODE+'~'+INTEGRATION_ID+'~'+PRODUCT_SALES_ORGANIZATION_NAME FROM [off].[TL_DIM_PRODUCT_SALES_ORGANIZATION]);

 --L2 - Brand Family (Winston Family)
 INSERT INTO  [off].[TL_DIM_PRODUCT_BRAND_FAMILY](CODE,INTEGRATION_ID,PRODUCT_BRAND_FAMILY_NAME,INSERTED_DATETIME)
		SELECT distinct CODE,INTEGRATION_ID,NAME, getdate() FROM [off].IN_CRM_Product_DIM where  VALID_TO = '9999-12-31 23:59:59.000' AND LEVEL = 'Brand Family'
		AND  CODE+'~'+INTEGRATION_ID+'~'+NAME NOT IN (SELECT CODE+'~'+INTEGRATION_ID+'~'+PRODUCT_BRAND_FAMILY_NAME FROM [off].[TL_DIM_PRODUCT_BRAND_FAMILY]);

-- L3 - Sub Category (RMC)
 INSERT INTO  [off].[TL_DIM_PRODUCT_SUB_CATEGORY](CODE,INTEGRATION_ID,PRODUCT_SUB_CATEGORY_NAME,INSERTED_DATETIME)
		SELECT distinct SUBCATEGORY AS CODE,SUBCATEGORY AS INTEGRATION_ID, SUBCATEGORY AS NAME, getdate() FROM [off].IN_CRM_Product_DIM where  SUBCATEGORY != 'Unspecified' and VALID_TO = '9999-12-31 23:59:59.000' AND LEVEL = 'Product'
		AND  SUBCATEGORY NOT IN (SELECT CODE FROM [off].[TL_DIM_PRODUCT_SUB_CATEGORY]);

-- L4 - Brand (Winston Brand)
 INSERT INTO  [off].[TL_DIM_PRODUCT_BRAND](CODE,INTEGRATION_ID,PRODUCT_BRAND_NAME,INSERTED_DATETIME)
		SELECT distinct CODE,INTEGRATION_ID,NAME, getdate() FROM [off].IN_CRM_Product_DIM where  VALID_TO = '9999-12-31 23:59:59.000' AND LEVEL = 'Brand'
		AND  CODE+'~'+INTEGRATION_ID+'~'+NAME NOT IN (SELECT CODE+'~'+INTEGRATION_ID+'~'+PRODUCT_BRAND_NAME FROM [off].[TL_DIM_PRODUCT_BRAND]);
--Insert product metrics
INSERT INTO [off].[TL_DIM_PRODUCT_METRICS]
           ([PRODUCT_SOURCE_ID]
           ,[PRODUCT_CODE]
           ,[PRODUCT_INTEGRATION_ID]
           ,[PRODUCT_STICK_PER_PACK]
           ,[PRODUCT_STICK_PER_CARTON]
           ,[PRODUCT_FORMAT]
           ,[PRODUCT_PRICE]
           ,[PRODUCT_CONVERSION_RATE]
           ,[PRODUCT_PRICE_SEGMENT]
           ,[VALID_FROM]
           ,[VALID_TO]
           ,[CHANGE_DATETIME]
           ,[INSERT_DATETIME])
	select		t.[_SK_PRODUCT] AS [PRODUCT_SOURCE_ID]
			   ,t.CODE as [PRODUCT_CODE]
			   ,t.INTEGRATION_ID as [PRODUCT_INTEGRATION_ID]
			   ,case when CODE LIKE 'DEV%' THEN 1
					 WHEN CODE LIKE 'XXXXXXX' THEN 4545.4545
				ELSE 20 END AS  [PRODUCT_STICK_PER_PACK]
			   ,case when CODE LIKE 'DEV%' THEN 1
					 WHEN CODE LIKE 'XXXXXXX' THEN 4545.4545
				ELSE 20 END *10 [PRODUCT_STICK_PER_CARTON]
			   ,'N/A' AS [PRODUCT_FORMAT]
			   ,NULL [PRODUCT_PRICE]
			   ,null [PRODUCT_CONVERSION_RATE]
			   ,null [PRODUCT_PRICE_SEGMENT]
			   ,202001 [VALID_FROM]
			   ,999912 [VALID_TO]
			   ,null[CHANGE_DATETIME]
			   ,getdate() [INSERT_DATETIME]
	 from [off].IN_CRM_Product_DIM t
	left join [off].TL_DIM_PRODUCT_METRICS pm on pm.PRODUCT_CODE = t.CODE 
	 where t.valid_to = '9999-12-31 23:59:59.000' and level = 'Product'
	 and CATEGORY = 'Tobacco' and SALES_ORGANIZATION = 'JTI'
	 and UPPER(t.code) NOT LIKE '%DUMMY%'
	 and pm.PRODUCT_CODE is null
-------------------------------------------


SELECT @v_cnt = count(*) from [off].LOG_DIM_PROCESSING where table_name = 'TL_DIM_PRODUCT' AND IN_PROCESSING_DATETIME = @DIMProcessDate;

IF @v_cnt = 0

BEGIN

	IF OBJECT_ID(N'tempdb..#tmp_dim_product') IS NOT NULL
	BEGIN
	DROP TABLE #tmp_dim_product
	END;



	with base (
			HASH_KEY
			,PRODUCT_SRC_KEY
			,CODE
			,INTEGRATION_ID
			,PRODUCT_NAME
			 -- CATEGORIES
			,PRODUCT_CATEGORY_KEY
			,PRODUCT_MANUFACTURER_KEY
			,PRODUCT_GENERAL_SALES_ORGANIZATION_KEY
			,PRODUCT_SALES_ORGANIZATION_KEY
			,PRODUCT_BRAND_FAMILY_KEY
			,PRODUCT_SUB_CATEGORY_KEY
			,PRODUCT_BRAND_KEY
			,PRODUCT_METRICS_KEY
			 -- VALIDITY
			,VALID_FROM
			,VALID_TO
			,DIM_VALID_FROM
	) as ( 
	SELECT 
	 CAST(HASHBYTES('SHA2_256',	ISNULL(CAST(t."_SK_PRODUCT" AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(t.CODE AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(t.INTEGRATION_ID  AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(t.NAME AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(cat.PRODUCT_CATEGORY_KEY AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(man.PRODUCT_MANUFACTURER_KEY AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(gso.PRODUCT_GENERAL_SALES_ORGANIZATION_KEY AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(ISNULL(l1.PRODUCT_SALES_ORGANIZATION_KEY,-1) AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(ISNULL(l2.PRODUCT_BRAND_FAMILY_KEY,-1) AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(ISNULL(l3.PRODUCT_SUB_CATEGORY_KEY,-1) AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(ISNULL(l4.PRODUCT_BRAND_KEY,-1) AS VARCHAR),'xxx###xxx') 
	) AS varbinary) AS HASH_KEY,
		t."_SK_PRODUCT" AS PRODUCT_SRC_KEY,
		t.CODE,
		t.INTEGRATION_ID,
		T.NAME AS PRODUCT_NAME,
		cat.PRODUCT_CATEGORY_KEY,
		man.PRODUCT_MANUFACTURER_KEY,
		gso.PRODUCT_GENERAL_SALES_ORGANIZATION_KEY,
		ISNULL(l1.PRODUCT_SALES_ORGANIZATION_KEY,-1) AS PRODUCT_SALES_ORGANIZATION_KEY,
		ISNULL(l2.PRODUCT_BRAND_FAMILY_KEY,-1) AS PRODUCT_BRAND_FAMILY_KEY,
		ISNULL(l3.PRODUCT_SUB_CATEGORY_KEY,-1) AS PRODUCT_SUB_CATEGORY_KEY,
		ISNULL(l4.PRODUCT_BRAND_KEY,-1) AS PRODUCT_BRAND_KEY,
		ISNULL(prm.PRODUCT_METRICS_KEY,-1) AS PRODUCT_METRICS_KEY,
		t.VALID_FROM,
		t.VALID_TO,
		adp.DIM_VALID_FROM
	 from [off].IN_CRM_Product_DIM t
		LEFT JOIN [off].[TL_DIM_PRODUCT_CATEGORY] cat on cat.PRODUCT_CATEGORY_NAME = t.CATEGORY
		LEFT JOIN [off].[TL_DIM_PRODUCT_MANUFACTURER] man on man.PRODUCT_MANUFACTURER_NAME = iSnull(t.MANUFACTURER,'COMPETITIVE ')
		LEFT JOIN [off].[TL_DIM_PRODUCT_GENERAL_SALES_ORGANIZATION] gso on gso.PRODUCT_GENERAL_SALES_ORGANIZATION_NAME = ISNULL(t.SALES_ORGANIZATION, 'JTI')
		LEFT JOIN [off].[TL_DIM_PRODUCT_SALES_ORGANIZATION] l1 
			on	l1.CODE = t.L1_CODE
			AND l1.PRODUCT_SALES_ORGANIZATION_NAME = t.L1_NAME
		LEFT JOIN [off].[TL_DIM_PRODUCT_BRAND_FAMILY] l2
			on	l2.CODE = t.L2_CODE
			AND l2.PRODUCT_BRAND_FAMILY_NAME = t.L2_NAME
		LEFT JOIN [off].[TL_DIM_PRODUCT_SUB_CATEGORY] l3
			on	l3.CODE = t.SUBCATEGORY
			--AND l3.PRODUCT_SUB_CATEGORY_NAME = t.SUBCATEGORY
		LEFT JOIN [off].[TL_DIM_PRODUCT_BRAND] l4
			on	l4.CODE = t.L4_CODE
			AND l4.PRODUCT_BRAND_NAME = t.L4_NAME
		LEFT JOIN [off].[TL_DIM_PRODUCT_METRICS] prm 
			on prm.PRODUCT_SOURCE_ID = t."_SK_PRODUCT" 
			AND prm.PRODUCT_CODE = t.CODE 
			AND prm.valid_from between t.valid_from and t.valid_to
		LEFT join (SELECT DISTINCT PRODUCT_SRC_KEY, FIRST_VALUE(VALID_FROM) OVER ( PARTITION BY PRODUCT_SRC_KEY ORDER BY VALID_TO DESC) DIM_VALID_FROM from [off].TL_DIM_PRODUCT) adp 
			on adp.PRODUCT_SRC_KEY = t."_SK_PRODUCT" 
	  where level = 'Product'
	)
	SELECT * into #tmp_dim_product FROM (
		select 
			COUNT(*) OVER (PARTITION BY PRODUCT_SRC_KEY) AS CNT
			   ,row_number() over (partition by PRODUCT_SRC_KEY ORDER BY VALID_FROM desc ) as rn
			   ,LAG(HASH_KEY,1,CAST('xxx###xxx' AS VARBINARY)) over(PARTITION BY PRODUCT_SRC_KEY ORDER BY VALID_FROM) AS PREV_HASH_KEY
			   ,LEAD(HASH_KEY,1,CAST('xxx###xxx' AS VARBINARY)) over(PARTITION BY PRODUCT_SRC_KEY ORDER BY VALID_FROM) AS NEXT_HASH_KEY
			   ,CASE WHEN DIM_VALID_FROM >= @V_ACT_DATE_KEY THEN 'U' 
					 WHEN DIM_VALID_FROM < @V_ACT_DATE_KEY THEN 'UI'
					 ELSE 'I'
					 END AS OP_FLAG 
		   ,BASE.*  from base
	) X
	where (  (HASH_KEY != PREV_HASH_KEY AND NEXT_HASH_KEY = CAST('xxx###xxx' AS VARBINARY) ) OR DIM_VALID_FROM IS NULL) AND RN=1 ;

	select @v_cnt = count(*) from #tmp_dim_product;

		IF @V_CNT != 0 
		BEGIN

		
	 --1. Ak je  VALID_FROM >= @V_ACT_DATE_KEY a VALID_TO = 999912
				--update all (prepis platneho zaznamu)
			MERGE INTO [off].TL_DIM_PRODUCT trg using 
				(select * from #tmp_dim_product WHERE OP_FLAG = 'U' ) src
			 on (src.PRODUCT_SRC_KEY = trg.PRODUCT_SRC_KEY AND trg.VALID_FROM >= @V_ACT_DATE_KEY AND trg.VALID_TO = 999912)
			WHEN MATCHED THEN UPDATE SET
				 trg.CODE = src.CODE
				,trg.INTEGRATION_ID = src.INTEGRATION_ID
				,trg.PRODUCT_NAME = src.PRODUCT_NAME
				,trg.PRODUCT_CATEGORY_KEY = src.PRODUCT_CATEGORY_KEY
				,trg.PRODUCT_MANUFACTURER_KEY = src.PRODUCT_MANUFACTURER_KEY
				,trg.PRODUCT_GENERAL_SALES_ORGANIZATION_KEY = src.PRODUCT_GENERAL_SALES_ORGANIZATION_KEY
				,trg.PRODUCT_SALES_ORGANIZATION_KEY = src.PRODUCT_SALES_ORGANIZATION_KEY
				,trg.PRODUCT_BRAND_FAMILY_KEY = src.PRODUCT_BRAND_FAMILY_KEY
				,trg.PRODUCT_SUB_CATEGORY_KEY = src.PRODUCT_SUB_CATEGORY_KEY
				,trg.PRODUCT_BRAND_KEY = src.PRODUCT_BRAND_KEY
				,trg.PRODUCT_METRICS_KEY = src.PRODUCT_METRICS_KEY
				,trg.CHANGED_DATETIME = @inProcessDatetime ;

	 --2. Ak je VALID_FROM <  @V_ACT_DATE_KEY a VALID_TO = 999912 
				-- update VALID_TO z 999912 na @V_ACT_DATE_KEY
				-- insert VALID_FROM = @V_NEXT_KEY
	MERGE INTO [off].TL_DIM_PRODUCT trg using 
				(select * from #tmp_dim_product WHERE OP_FLAG = 'UI' ) src
			 on (src.PRODUCT_SRC_KEY = trg.PRODUCT_SRC_KEY AND trg.VALID_FROM < @V_ACT_DATE_KEY AND trg.VALID_TO = 999912)
			WHEN MATCHED THEN UPDATE SET
				trg.VALID_TO = @V_ACT_DATE_KEY
				,trg.CHANGED_DATETIME = @inProcessDatetime;

			INSERT INTO [off].TL_DIM_PRODUCT (
							PRODUCT_SRC_KEY
							,CODE
							,INTEGRATION_ID
							,PRODUCT_NAME
							,PRODUCT_CATEGORY_KEY
							,PRODUCT_MANUFACTURER_KEY
							,PRODUCT_GENERAL_SALES_ORGANIZATION_KEY
							,PRODUCT_SALES_ORGANIZATION_KEY
							,PRODUCT_BRAND_FAMILY_KEY
							,PRODUCT_SUB_CATEGORY_KEY
							,PRODUCT_BRAND_KEY
							,PRODUCT_METRICS_KEY
							,VALID_FROM
							,VALID_TO
							,CHANGED_DATETIME
							,INSERTED_DATETIME ) 
				SELECT  PRODUCT_SRC_KEY
						,CODE
						,INTEGRATION_ID
						,PRODUCT_NAME
						,PRODUCT_CATEGORY_KEY
						,PRODUCT_MANUFACTURER_KEY
						,PRODUCT_GENERAL_SALES_ORGANIZATION_KEY
						,PRODUCT_SALES_ORGANIZATION_KEY
						,PRODUCT_BRAND_FAMILY_KEY
						,PRODUCT_SUB_CATEGORY_KEY
						,PRODUCT_BRAND_KEY
						,PRODUCT_METRICS_KEY
						,@V_NEXT_DATE_KEY
						,999912
						,null
						,@inProcessDatetime
				FROM #tmp_dim_product WHERE OP_FLAG = 'UI'
	 --3. Ak je VALID_FROM < @V_ACT_DATE_KEY a VALID_FROM < 999912
				-- insert VALID_FROM = @V_ACT_DATE_KEY a VALID_TO = 999912
			 INSERT INTO [off].TL_DIM_PRODUCT (
							PRODUCT_SRC_KEY
							,CODE
							,INTEGRATION_ID
							,PRODUCT_NAME
							,PRODUCT_CATEGORY_KEY
							,PRODUCT_MANUFACTURER_KEY
							,PRODUCT_GENERAL_SALES_ORGANIZATION_KEY
							,PRODUCT_SALES_ORGANIZATION_KEY
							,PRODUCT_BRAND_FAMILY_KEY
							,PRODUCT_SUB_CATEGORY_KEY
							,PRODUCT_BRAND_KEY
							,PRODUCT_METRICS_KEY
							,VALID_FROM
							,VALID_TO
							,CHANGED_DATETIME
							,INSERTED_DATETIME  ) 
				SELECT  PRODUCT_SRC_KEY
						,CODE
						,INTEGRATION_ID
						,PRODUCT_NAME
						,PRODUCT_CATEGORY_KEY
						,PRODUCT_MANUFACTURER_KEY
						,PRODUCT_GENERAL_SALES_ORGANIZATION_KEY
						,PRODUCT_SALES_ORGANIZATION_KEY
						,PRODUCT_BRAND_FAMILY_KEY
						,PRODUCT_SUB_CATEGORY_KEY
						,PRODUCT_BRAND_KEY
						,PRODUCT_METRICS_KEY
						,@V_NEXT_DATE_KEY
						,999912
						,null
						,@inProcessDatetime
				FROM #tmp_dim_product WHERE OP_FLAG = 'I'

	END;


	insert into [off].LOG_DIM_PROCESSING values ('TL_DIM_PRODUCT',@DIMProcessDate,@inProcessDatetime);


	IF OBJECT_ID(N'tempdb..#tmp_dim_product') IS NOT NULL
	BEGIN
	DROP TABLE #tmp_dim_product
	END;
END;


END;