USE [ClusterDWH]
GO
/****** Object:  StoredProcedure [off].[MERGE_TL_DIM_ACCOUNT]    Script Date: 8/3/2026 1:01:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [off].[MERGE_TL_DIM_ACCOUNT] (@inDIMProcessDate datetime,@inProcessDatetime datetime)
as 
BEGIN

DECLARE @CNT_PROCESSED	int = 0 ;
DECLARE @V_ACT_DATE_KEY int;
DECLARE @V_NEXT_DATE_KEY int;
DECLARE @V_CNT INT;
DECLARE @DIMProcessDate DATETIME;

SELECT @DIMProcessDate = max(valid_from) from [off].IN_CRM_Account_DIM;

SELECT @V_ACT_DATE_KEY =  CAST(CONVERT(NVARCHAR(6), @DIMProcessDate, 112) AS INTEGER);
SELECT @V_NEXT_DATE_KEY = CAST(CONVERT(NVARCHAR(6), DATEADD(month, 1,@DIMProcessDate ), 112) AS INTEGER);

SELECT @v_cnt = count(*) from [off].LOG_DIM_PROCESSING where table_name = 'TL_DIM_ACCOUNT' AND IN_PROCESSING_DATETIME = @DIMProcessDate;

-- STATIC DIMENSIONS
---------------------------------------------------------------------------------------------------------------------
	 INSERT INTO [off].[TL_DIM_ACCOUNT_CHANNEL] (ACCOUNT_CHANNEL_NAME,inserted_datetime) 
		SELECT DISTINCT MARKET_CHANNEL,getdate() FROM [off].IN_CRM_Account_DIM where  VALID_TO = '9999-12-31 23:59:59.000' 
		AND  MARKET_CHANNEL NOT IN (SELECT ACCOUNT_CHANNEL_NAME FROM [off].[TL_DIM_ACCOUNT_CHANNEL]);

	INSERT INTO [off].[TL_DIM_ACCOUNT_SUBCHANNEL] (ACCOUNT_SUBCHANNEL_NAME,inserted_datetime) 
		SELECT DISTINCT TRADE_SEGMENT,getdate() FROM [off].IN_CRM_Account_DIM where  VALID_TO = '9999-12-31 23:59:59.000' 
		AND  TRADE_SEGMENT NOT IN (SELECT ACCOUNT_SUBCHANNEL_NAME FROM [off].[TL_DIM_ACCOUNT_SUBCHANNEL]);

	INSERT INTO [off].[TL_DIM_ACCOUNT_FORMAT] (ACCOUNT_FORMAT_NAME,inserted_datetime) 
		SELECT DISTINCT CLASS,getdate() FROM [off].IN_CRM_Account_DIM where  VALID_TO = '9999-12-31 23:59:59.000' 
		AND  CLASS NOT IN (SELECT ACCOUNT_FORMAT_NAME FROM [off].[TL_DIM_ACCOUNT_FORMAT]);

	INSERT INTO [off].[TL_DIM_ACCOUNT_SUBFORMAT] (ACCOUNT_SUBFORMAT_NAME,inserted_datetime) 
		SELECT DISTINCT TYPE,getdate() FROM [off].IN_CRM_Account_DIM where  VALID_TO = '9999-12-31 23:59:59.000' 
		AND  TYPE NOT IN (SELECT ACCOUNT_SUBFORMAT_NAME FROM [off].[TL_DIM_ACCOUNT_SUBFORMAT]);

---------------------------------------------------------------------------------------------------------------------

IF @v_cnt = 0
BEGIN

	IF OBJECT_ID(N'tempdb..#tmp_dim_account') IS NOT NULL
	BEGIN
	DROP TABLE #tmp_dim_account
	END;


	WITH parent  ( EMP_USERNAME,PARENT_ACCOUNT,"_SK_ACCOUNT")
	as (
	SELECT CASE WHEN CNT = 7 THEN L1_EMP_USERNAME
			WHEN CNT = 6 THEN L2_EMP_USERNAME
			WHEN CNT = 5 THEN L3_EMP_USERNAME
			WHEN CNT = 4 THEN L4_EMP_USERNAME
			WHEN CNT = 3 THEN L5_EMP_USERNAME
			WHEN CNT = 2 THEN L6_EMP_USERNAME
			WHEN CNT = 1 THEN L6_EMP_USERNAME
			ELSE NULL END AS EMP_USERNAME,
	   CASE WHEN CNT_ACC = 4 THEN L1_ACCOUNT_CODE
			WHEN CNT_ACC = 3 THEN L2_ACCOUNT_CODE
			WHEN CNT_ACC = 2 THEN L3_ACCOUNT_CODE
			WHEN CNT_ACC = 1 THEN L4_ACCOUNT_CODE
			ELSE NULL END AS PARENT_ACCOUNT,
			"_SK_ACCOUNT" 
			 FROM 
		(
			select 
			(
			IIF(L1_EMP_USERNAME=L2_EMP_USERNAME, 1, 0)
			+
			IIF(L2_EMP_USERNAME=L3_EMP_USERNAME, 1, 0)
			+
			IIF(L3_EMP_USERNAME=L4_EMP_USERNAME, 1, 0)
			+
			IIF(L4_EMP_USERNAME=L5_EMP_USERNAME, 1, 0)
			+
			IIF(L5_EMP_USERNAME=L6_EMP_USERNAME, 1, 0)
			+
			IIF(L6_EMP_USERNAME=L7_EMP_USERNAME, 1, 0) ) AS CNT
			,
			(1
			+
			IIF(L1_ACCOUNT_CODE=L2_ACCOUNT_CODE, 1, 0)
			+
			IIF(L2_ACCOUNT_CODE=L3_ACCOUNT_CODE, 1, 0)
			+
			IIF(L3_ACCOUNT_CODE=L4_ACCOUNT_CODE, 1, 0)
			+
			IIF(L4_ACCOUNT_CODE=L5_ACCOUNT_CODE, 1, 0)

			 ) AS CNT_ACC
			,*
			 FROM [off].IN_CRM_Account_DIM n
			 WHERE   n.VALID_TO = '9999-12-31 23:59:59.000' 
			 ) AS X  )		
	, base (
			HASH_KEY
			,ACCOUNT_SRC_KEY
			,TERRITORY_SRC_KEY
			,ACCOUNT_CODE
			,CODE_2
			,ACCOUNT_NAME
			 -- ADDRESS
			,STREET
			,CITY
			,POSTAL_CODE
			,REGION
			,COUNTRY
			 -- CONTACT
			,PHONE_NUM
			,EMAIL_ADDRESS
			 -- KEYS
			,ACCOUNT_CHANNEL_KEY
			,ACCOUNT_SUBCHANNEL_KEY
			,ACCOUNT_FORMAT_KEY
			,ACCOUNT_SUBFORMAT_KEY
			,PARENT_ACCOUNT_KEY
			,USER_KEY
			,MUNICIPALITY_KEY  
			,VISIT_FREQUENCY
			,STATUS
			,LATITUDE
			,LONGITUDE
			,VALID_FROM
			,VALID_TO
			,DIM_VALID_FROM
	) as ( 
	SELECT  DISTINCT
	 CAST(HASHBYTES('SHA2_256',	ISNULL(CAST(n."_SK_ACCOUNT" AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n."_SK_PRIMARY_TERRITORY" AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.CODE  AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.CODE_2  AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.NAME AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.MARKET_CHANNEL AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.TRADE_SEGMENT AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.CLASS AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.TYPE AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.ADDRESS_LINE_1 AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.CITY AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.POSTAL_CODE AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.STATE AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.COUNTRY AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.PHONE_NB AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.EMAIL_ADDRESS AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(isnull(a.account_nk,-1) AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(u.USER_NK AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(x.MUNICIPALITY_KEY AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.VISIT_FREQUENCY AS VARCHAR),'xxx###xxx')  +
							ISNULL(CAST(n.STATUS AS VARCHAR),'xxx###xxx') 
	) AS varbinary) AS HASH_KEY
	 ,n."_SK_ACCOUNT" AS ACCOUNT_SRC_KEY
	 ,n."_SK_PRIMARY_TERRITORY" AS TERRITORY_SRC_KEY
	 ,n.CODE AS ACCOUNT_CODE
	 ,n.CODE_2
	 ,n.NAME AS ACCOUNT_NAME
	 -- ADDRESS
	 ,n.ADDRESS_LINE_1 AS STREET
	 ,n.CITY AS CITY
	 ,n.POSTAL_CODE AS POSTAL_CODE
	 ,n.STATE AS REGION
	 ,n.COUNTRY AS COUNTRY
	 -- CONTACT
	 ,n.PHONE_NB AS PHONE_NUM
	 ,n.EMAIL_ADDRESS AS EMAIL_ADDRESS
	 -- KEYS
	 --,
	 ,isnull(ch.ACCOUNT_CHANNEL_KEY,-1) AS ACCOUNT_CHANNEL_KEY
	 ,isnull(sch.ACCOUNT_SUBCHANNEL_KEY,-1) AS ACCOUNT_SUBCHANNEL_KEY
	 ,isnull(f.ACCOUNT_FORMAT_KEY,-1) AS ACCOUNT_FORMAT_KEY
	 ,isnull(sf.ACCOUNT_SUBFORMAT_KEY,-1) AS ACCOUNT_SUBFROMAT_KEY

	 ,isnull(a.ACCOUNT_NK,-1) AS PARENT_ACCOUNT_KEY
	 ,isnull(u.USER_NK,-1)  AS USER_KEY
	 ,isnull(x.MUNICIPALITY_KEY,-1) AS  MUNICIPALITY_KEY 
 
	 ,n.VISIT_FREQUENCY AS VISIT_FREQUENCY
	 ,n.STATUS as STATUS
	 ,n.LATITUDE
	 ,n.LONGITUDE
	 ,n.VALID_FROM
	 ,n.VALID_TO
	 ,adp.DIM_VALID_FROM
	FROM [off].IN_CRM_Account_DIM n
		JOIN parent on parent."_SK_ACCOUNT" = n."_SK_ACCOUNT"
		LEFT JOIN [off].TL_DIM_ACCOUNT a on n."_SK_PARENT_ACCOUNT" = a.account_src_key and a.valid_to = 999912
		LEFT JOIN [off].[TL_DIM_ACCOUNT_CHANNEL] ch on ch.ACCOUNT_CHANNEL_NAME = n.MARKET_CHANNEL
		LEFT JOIN [off].[TL_DIM_ACCOUNT_SUBCHANNEL] sch on sch.ACCOUNT_SUBCHANNEL_NAME = n.TRADE_SEGMENT
		LEFT JOIN [off].[TL_DIM_ACCOUNT_FORMAT] f on f.ACCOUNT_FORMAT_NAME = n.CLASS
		LEFT JOIN [off].[TL_DIM_ACCOUNT_SUBFORMAT] sf on sf.ACCOUNT_SUBFORMAT_NAME = n.TYPE
		LEFT JOIN [off].[TL_DIM_USER] u on u."USER_NAME" = parent.EMP_USERNAME AND u.VALID_TO = 999912
		LEFT JOIN 	(select a."_SK_ACCOUNT" AS id, a.POSTAL_CODE ,a.CITY ,ISNULL(ISNULL(m.MUNICIPALITY_KEY,X.MUNICIPALITY_KEY),-1) as MUNICIPALITY_KEY,
						 ROW_NUMBER() OVER(PARTITION BY a."_SK_ACCOUNT" ORDER BY (CASE WHEN m.COUNTY_NAME = a.STATE THEN 1 ELSE 999 END),a.valid_to desc, a.POSTAL_CODE ASC) rid
				from [off].IN_CRM_Account_DIM A
				left join  (SELECT m.MUNICIPALITY_KEY,MUNICIPALITY_CODE,m.MUNICIPALITY_NAME,c.COUNTY_NAME FROM [off].TL_DIM_MUNICIPALITY M
								LEFT JOIN  [off].TL_DIM_COUNTY c ON M.COUNTY_KEY = C.COUNTY_KEY ) m
					on [off].Format_RemoveAccents(m.MUNICIPALITY_NAME) = [off].Format_RemoveAccents(a.CITY)
				left join [off].MAPPING_MUNICIPALITY_POSTALCODE p on p.MUNICIPALITY_CODE = m.MUNICIPALITY_CODE
					AND p.POSTALCODE = (case when len(REPLACE(a.POSTAL_CODE,' ','')) = 4 then '0'+REPLACE(a.POSTAL_CODE,' ','') else REPLACE(a.POSTAL_CODE,' ','') end)
				left join ( SELECT m.MUNICIPALITY_KEY,M.MUNICIPALITY_NAME,POSTALCODE,m.type, ROW_NUMBER() OVER(PARTITION BY pm.POSTALCODE ORDER BY m.TYPE ASC) rid  FROM [off].MAPPING_MUNICIPALITY_POSTALCODE pm
									left join [off].TL_DIM_MUNICIPALITY m ON m.MUNICIPALITY_CODE = pm.MUNICIPALITY_CODE
				
									) x on x.POSTALCODE = a.POSTAL_CODE
										 and x.RID = 1
				where a.valid_to  = '9999-12-31 23:59:59.000') x 
			on x.RID = 1 AND x.ID = n."_SK_ACCOUNT"
		LEFT join (SELECT DISTINCT ACCOUNT_SRC_KEY, FIRST_VALUE(VALID_FROM) OVER ( PARTITION BY ACCOUNT_SRC_KEY ORDER BY VALID_TO DESC) DIM_VALID_FROM from [off].TL_DIM_ACCOUNT) adp 
				on adp.account_src_key = n.[_SK_ACCOUNT]
	)
	SELECT * into #tmp_dim_account FROM (
		select 
			COUNT(*) OVER (PARTITION BY ACCOUNT_SRC_KEY) AS CNT
				,row_number() over (partition by ACCOUNT_SRC_KEY ORDER BY VALID_FROM desc ) as rn
			   ,LAG(HASH_KEY,1,CAST('xxx###xxx' AS VARBINARY)) over(PARTITION BY ACCOUNT_SRC_KEY ORDER BY VALID_FROM) AS PREV_HASH_KEY
			   ,LEAD(HASH_KEY,1,CAST('xxx###xxx' AS VARBINARY)) over(PARTITION BY ACCOUNT_SRC_KEY ORDER BY VALID_FROM) AS NEXT_HASH_KEY
			   ,CASE WHEN DIM_VALID_FROM >= @V_ACT_DATE_KEY THEN 'U' 
					 WHEN DIM_VALID_FROM < @V_ACT_DATE_KEY THEN 'UI'
					 ELSE 'I'
					 END AS OP_FLAG 
		   ,BASE.*  from base
	) X
	where (  (HASH_KEY != PREV_HASH_KEY AND NEXT_HASH_KEY = CAST('xxx###xxx' AS VARBINARY) ) OR DIM_VALID_FROM IS NULL) AND RN=1 ;


	select @v_cnt = count(*) from #tmp_dim_account;

		IF @V_CNT != 0 
		BEGIN


	 --1. Ak je  VALID_FROM >= @V_ACT_DATE_KEY a VALID_TO = 999912
				--update all (prepis platneho zaznamu)
			MERGE INTO [off].TL_DIM_ACCOUNT trg using 
				(select * from #tmp_dim_account WHERE OP_FLAG = 'U' ) src
			 on (src.ACCOUNT_SRC_KEY = trg.ACCOUNT_SRC_KEY AND trg.VALID_FROM >= @V_ACT_DATE_KEY AND trg.VALID_TO = 999912)
			WHEN MATCHED THEN UPDATE SET
				 trg.TERRITORY_SRC_KEY = src.TERRITORY_SRC_KEY
				,trg.ACCOUNT_CODE = src.ACCOUNT_CODE
				,trg.CODE_2 = src.CODE_2
				,trg.ACCOUNT_NAME = src.ACCOUNT_NAME
				,trg.STREET = src.STREET
				,trg.CITY = src.CITY
				,trg.POSTAL_CODE = src.POSTAL_CODE
				,trg.REGION = src.REGION
				,trg.COUNTRY = src.COUNTRY
				,trg.PHONE_NUM = src.PHONE_NUM
				,trg.EMAIL_ADDRESS = src.EMAIL_ADDRESS
				,trg.ACCOUNT_CHANNEL_KEY = src.ACCOUNT_CHANNEL_KEY
				,trg.ACCOUNT_SUBCHANNEL_KEY = src.ACCOUNT_SUBCHANNEL_KEY
				,trg.ACCOUNT_FORMAT_KEY = src.ACCOUNT_FORMAT_KEY
				,trg.ACCOUNT_SUBFORMAT_KEY = src.ACCOUNT_SUBFORMAT_KEY
				,trg.PARENT_ACCOUNT_KEY = src.PARENT_ACCOUNT_KEY
				,trg.USER_KEY = src.USER_KEY
				,trg.MUNICIPALITY_KEY = src.MUNICIPALITY_KEY
				,trg.VISIT_FREQUENCY = src.VISIT_FREQUENCY
				,trg.STATUS = src.STATUS
				,trg.LATITUDE = src.LATITUDE
				,trg.LONGITUDE = src.LONGITUDE
				,trg.CHANGED_DATETIME = @inProcessDatetime ;

	 --2. Ak je VALID_FROM <  @V_ACT_DATE_KEY a VALID_TO = 999912 
				-- update VALID_TO z 999912 na @V_ACT_DATE_KEY
				-- insert VALID_FROM = @V_NEXT_KEY
	MERGE INTO [off].TL_DIM_ACCOUNT trg using 
				(select * from #tmp_dim_account WHERE OP_FLAG = 'UI' ) src
			 on (src.ACCOUNT_SRC_KEY = trg.ACCOUNT_SRC_KEY AND trg.VALID_FROM < @V_ACT_DATE_KEY AND trg.VALID_TO = 999912)
			WHEN MATCHED THEN UPDATE SET
				trg.VALID_TO = @V_ACT_DATE_KEY
				,trg.CHANGED_DATETIME = @inProcessDatetime;

			INSERT INTO [off].TL_DIM_ACCOUNT (
							ACCOUNT_SRC_KEY
							,TERRITORY_SRC_KEY
							,ACCOUNT_CODE
							,CODE_2
							,ACCOUNT_NAME
							,STREET
							,CITY
							,POSTAL_CODE
							,REGION
							,COUNTRY
							,PHONE_NUM
							,EMAIL_ADDRESS
							,ACCOUNT_CHANNEL_KEY
							,ACCOUNT_SUBCHANNEL_KEY
							,ACCOUNT_FORMAT_KEY
							,ACCOUNT_SUBFORMAT_KEY
							,PARENT_ACCOUNT_KEY
							,USER_KEY
							,MUNICIPALITY_KEY
							,VISIT_FREQUENCY
							,STATUS
							,LATITUDE
							,LONGITUDE
							,VALID_FROM
							,VALID_TO
							,CHANGED_DATETIME
							,INSERTED_DATETIME ) 
				SELECT  ACCOUNT_SRC_KEY
						,TERRITORY_SRC_KEY
						,ACCOUNT_CODE
						,CODE_2
						,ACCOUNT_NAME
						,STREET
						,CITY
						,POSTAL_CODE
						,REGION
						,COUNTRY
						,PHONE_NUM
						,EMAIL_ADDRESS
						,ACCOUNT_CHANNEL_KEY
						,ACCOUNT_SUBCHANNEL_KEY
						,ACCOUNT_FORMAT_KEY
						,ACCOUNT_SUBFORMAT_KEY
						,PARENT_ACCOUNT_KEY
						,USER_KEY
						,MUNICIPALITY_KEY
						,VISIT_FREQUENCY
						,STATUS
						,LATITUDE
						,LONGITUDE
						,@V_NEXT_DATE_KEY
						,999912
						,null
						,@inProcessDatetime
				FROM #tmp_dim_account WHERE (OP_FLAG = 'UI')
	 --3. Ak je VALID_FROM < @V_ACT_DATE_KEY a VALID_FROM < 999912
				-- insert VALID_FROM = @V_ACT_DATE_KEY a VALID_TO = 999912
			 INSERT INTO [off].TL_DIM_ACCOUNT (
							ACCOUNT_SRC_KEY
							,TERRITORY_SRC_KEY
							,ACCOUNT_CODE
							,CODE_2
							,ACCOUNT_NAME
							,STREET
							,CITY
							,POSTAL_CODE
							,REGION
							,COUNTRY
							,PHONE_NUM
							,EMAIL_ADDRESS
							,ACCOUNT_CHANNEL_KEY
							,ACCOUNT_SUBCHANNEL_KEY
							,ACCOUNT_FORMAT_KEY
							,ACCOUNT_SUBFORMAT_KEY
							,PARENT_ACCOUNT_KEY
							,USER_KEY
							,MUNICIPALITY_KEY
							,VISIT_FREQUENCY
							,STATUS
							,LATITUDE
							,LONGITUDE
							,VALID_FROM
							,VALID_TO
							,CHANGED_DATETIME
							,INSERTED_DATETIME ) 
				SELECT  ACCOUNT_SRC_KEY
						,TERRITORY_SRC_KEY
						,ACCOUNT_CODE
						,CODE_2
						,ACCOUNT_NAME
						,STREET
						,CITY
						,POSTAL_CODE
						,REGION
						,COUNTRY
						,PHONE_NUM
						,EMAIL_ADDRESS
						,ACCOUNT_CHANNEL_KEY
						,ACCOUNT_SUBCHANNEL_KEY
						,ACCOUNT_FORMAT_KEY
						,ACCOUNT_SUBFORMAT_KEY
						,PARENT_ACCOUNT_KEY
						,USER_KEY
						,MUNICIPALITY_KEY
						,VISIT_FREQUENCY
						,STATUS
						,LATITUDE
						,LONGITUDE
						,202001
						,999912
						,null
						,@inProcessDatetime
				FROM #tmp_dim_account WHERE OP_FLAG = 'I'

	END;

	insert into [off].LOG_DIM_PROCESSING values ('TL_DIM_ACCOUNT',@DIMProcessDate,@inProcessDatetime);


	IF OBJECT_ID(N'tempdb..#tmp_dim_account') IS NOT NULL
	BEGIN
	DROP TABLE #tmp_dim_account
	END;
END;

END;